### ISSUE TITLE
Proposal for Web3 Game Inspired by Splinterlands and Clash Royale with Enhanced Privacy Using FHEVM

### ISSUE THREAD

**Issue by Uday-kiran9147** [zama-ai/bounty-and-grant-program#104]
# Proposal for Web3 Game Inspired by Splinterlands and Clash Royale with Enhanced Privacy Using FHEVM

## Bounty Details:
- *Bounty Name:* Proposal for Web3 Game Inspired by Splinterlands and Clash Royale with Enhanced Privacy Using FHEVM
- *Bounty Type:* Major Bounty
- *Library Targeted:* ```Fhevm```
- *Reward:* € 6500

## Introduction:
The world is increasingly focusing on Web3 games. However, one of the main challenges facing Web3 games is ensuring privacy between players while maintaining the integrity of the gaming experience.

Revenue of Splinterlands is [$30 million](https://avocadodao.io/posts/the-most-popular-and-profitable-nft-games-in-2023-1761#:~:text=Splinterlands%20is%20the%20second%20most,BSC%2C%20WAX%2C%20and%20ETH) per month 

Revenue of Clash Royale is [$4 billion](https://www.businessofapps.com/data/clash-royale-statistics/#:~:text=The%20real%2Dtime%20strategy%20game,than%20%244%20billion%20in%20revenue.
)

 

### Components:
- 16 unique NFT troops (each with Attack, Defense, and Mana cost)
- Deck-building system (allows players to choose 8 troops from the 16)
- Objective: Defeat your opponent by reducing their health to zero.

### Gameplay:
- *Deck Building:* Before the match, players choose 8 troops from their collection to form their deck.
- *Match Start:* At the beginning of the match, both players are randomly dealt a hand of 4 troops from their deck.
- *Turn Structure:* Each turn, players alternate between taking two actions: Attack and Defense. Players also have the option to play a troop from their hand or draw a new one.
- *Mana System:* Each troop has a Mana cost, and successful defense grants the player additional Mana.
- *Winning:* The player who reduces their opponent's health to zero wins the game.

### Game Flow

In this game, users will be given 16 NFT Troops. Before starting a match, the user has to choose a deck of 8 troops according to their strategy. Similar to traditional Clash Royale, the user will be given a random selection of 4 troops from their deck at the beginning of the match. 

During the match, players take turns placing one troop at a time according to the game rules. If the attack of troops dominates, the opponent's health will be decreased. If a player runs out of MANA, they must play defense to increase their Mana. If a player reduces the opponent's health to zero, they will be declared the winner.

### Game Rules

- If both Players choose Attack, both Players' Health is decreased by the respective amount.
- If Player 1 chooses Attack and Player 2 chooses Defence, Player 2's health will decrease by (Player 1’s ATTACK - Player 2’s DEFENCE) only if Player 1’s ATTACK > Player 2’s DEFENCE.
- If Player 1 chooses Defence and Player 2 chooses Attack, Player 1's health will decrease by (Player 2’s ATTACK - Player 1’s DEFENCE) only if Player 2’s ATTACK > Player 1’s DEFENCE.
- If both Players choose Defence, there will be no change in Health.
- Whenever a Player attacks with a troop, the MANA of the Player will be reduced by the MANA cost of the respective troop.
- Whenever a Player defends with a troop, the MANA of the Player will be increased by the MANA cost of the respective troop.

## Additional Part of the Game

An additional feature we can introduce is special troops that players can obtain by completing specific tasks. For example, players may unlock special troops by following Zama on LinkedIn or engaging in other social media activities. These special troops will have enhanced powers compared to the original troops, adding an element of uniqueness and reward to the game.

 

## Difficulties of Project:
- Implementation of New Encrypted-NFT for Each Troop
- Creating a Deck System with Euint of Zama’s Fhevm
- Selecting 4 Random Troops [Encryptedly]
- Implementing Battle System of Selected Troops (attack/defense)

## Deliverables:
The deliverables will be an MVP (minimum viable product) consisting of:
1. Smart contract of the project
2. Frontend showcasing the effective use of FHEVM in Web3 gaming
3. Tests for smart contract
4. Documentation and tutorial of the project's workings

## Timeline:
Since this project is a major one, it is estimated to take around 45-70 days.

## Conclusion:
Our proposal outlines a Web3 game inspired by Clash Royale and Splinterlands, incorporating FHEVM technology to address privacy concerns and enhance security. By leveraging decentralized technologies such as blockchain and cryptographic protocols, we aim to create a game that offers a secure, transparent, and engaging gaming experience for players worldwide. We believe that our project has the potential to set a new standard for privacy-preserving Web3 games while capturing the imagination of gamers everywhere.

Thank you for considering our grant proposal.

Warm regards,

Uday-Kiran9147

**Comment by zaccherinij** [comment]
We'll get back to you soon about this! Thanks for your patience!

**Comment by aquint-zama** [comment]
Hello @Uday-kiran9147,

We took some time to decide as you did a great job explaining your proposal. It's definitely a good idea and a good project to showcase fhevm but it is not really fitting the grant program goal, as we want to showcase new usages of encrypted blockchain and this one is too close to our previous bounty program topic (creating an on chain game).

I am gonna close this grant proposal but if you are motivated it's definitely a good idea to build this project.
