### ISSUE TITLE
Private NFT Auctions

### ISSUE THREAD

**Issue by kroist** [zama-ai/bounty-and-grant-program#106]
# Zama Grant Program: Application

Please give us as much information as possible on the project you would like to submit. You can find inspiration from our existing list of grants.

- Library targeted: **fhEVM**

- Overview: On-chain NFT private auctions, where the bids are revealed ONLY to auction participants.

### Motivation
Public auctions are open to everyone to join and make bids, offering transparentness to the whole process.
Private auctions are closed sales of assets, where the participants don't want to involve public to the sale because of various reasons. Currently, private auctions of on-chain data are done off-chain either by moving trust to third-party or they require complex cryptographic setup. Blockchain smart contract offer the trustless execution of the code. fhEVM also offers private execution of smart contracts.

We propose the on-chain auction system, which is open ONLY to participants, which fulfil the requirements of participation. The proposed implementation has a stake, minimal bid and a fee for entering the auction.

### Technicality
The system works as follows:
- Auction is initiated by seller, the `stake`, `minimal bid`, `participation fee` are established in smart contract's constructor. After that, the `minimal bid` becomes the `current bid` and is encrypted. The `access key` is generated, which is encrypted and stored into NFT.
- There is a window for participants to enter the auction, by leaving a stake and paying a fee. They mint an NFT with and `access key`.
- The auction is started. Participants of the auction can re-encrypt the current bid using the `access key` and outbid it, by submitting the new encrypted price. Before submitting the new price, they should also approve their private ERC-20 token to the auction smart contract.
- At the end of the auction, the highest bidder receives the ownership of an NFT.

### Milestones

There are two things to implement:
1. Smart contracts for the auction.
2. Front-end client

### Reward
7k-15k €

### Follow-up Considerations

It might be also feasible to hide the identities of the auction participants, by introduction of privacy pool and submission of ZKP at each operation for securely proving the identity of participant. But it would enlarge the scope of the bounty a lot. And it would not use fhEVM :)

**Comment by Akinasan** [comment]
Well done!

**Comment by Matthis-Herbrecht** [comment]
Congrats

**Comment by jatZama** [comment]
Hello @kroist 
The idea is interesting but there are 2 points that are not clear for me:
1/ More importantly I don't understand at all why would we need the access key. Regular reencryption would be enough, knowing that we already have access control in the smart contract logic (i.e only those who paid the fee and staked some amount are allowed to participate, so same logic can be required for those allowed to do reencryption of the winning amount).
2/ This is a minor point compared to 1/: is the staking by participants absolutely needed?  they already have to pay a fee to be whitelisted for the auction, so it seems we dont absolutely need an additional stake. However I can see an advantage to this, if we want to limit sybil attacks for some reason (for example we could also limit the number of reencryptions for each participating account, and if the participating fee is too low then this staking would make sense), ultimately this is related to tokenomics considerations.

I would add that the contract would even become more interesting if it leverages more FHE operations. For example we could only allow new bids if they are above some specific percentage compared to previous winning bids. This would require real FHE (using TFHE.mul and TFHE.gte on top of the TFHE.add in the token amount), and would even make more sense tokenomic-wise, as it avoids spamming behavior by just increasing current winning bid by a single token. Also a more complex kind of auction like Vickerey auction is an easy feature to add, and rate limiting the number of reencryption or timelocks to avoid spamming behavior , etc...

**Comment by zaccherinij** [comment]
@kroist did you get a chance to check out @jatZama's reply above? Without any feedback from you, we will close this issue.

Cheers,
JZ

**Comment by zaccherinij** [comment]
Hey @kroist,

Just a heads up that we will not follow up on this grant, we have well received your submission for the Zama Bounty Program  S5 though :)

Cheers,
JZ
