### ISSUE TITLE
MinaDeck<enter Project name>

### ISSUE THREAD

**Issue by Saurus9290** [zama-ai/bounty-and-grant-program#112]
# Zama Grant Program: Application

Please give us as much information as possible on the project you would like to submit. You can find inspiration from our existing list of grants.

- Library targeted:

- Overview:

- Description:

- Reward:

- Related links and reference:

**Comment by aquint-zama** [comment]
Hello @Saurus9290, if you need time to create your Grant proposal it's better to close this issue and open a new one when ready.
If you already have more information, please update the description.
