### ISSUE TITLE
Scola ML

### ISSUE THREAD

**Issue by yojedesign** [zama-ai/bounty-and-grant-program#114]
# Zama Grant Program: Application

Name : Scola ML
Please give us as much information as possible on the project you would like to submit. You can find inspiration from our existing list of grants.

- Library targeted: Concrete ML

- Overview: Developing a sophisticated, multi-layered linear model for enhanced threat prediction.

- Description: The project aims to build an linear model using the Concrete ML library, which would improve threat prediction accuracy by learning from a broader set of indicators and implementing more complex pattern recognition.

- Reward:  $10,000 

- Related links and reference:

https://export.arxiv.org/pdf/2303.13621v1.pdf
https://www.springerprofessional.de/the-need-for-a-transdisciplinary-approach-to-security-of-cyber-p/1883138

**Comment by andrei-stoian-zama** [comment]
Thank you for the grant proposal!

Could you go a bit more in the detail about the type of model and pipeline that you would want to build? We'd like to understand which parts of this pipeline would be in FHE and what the FHE model architecture would be.

**Comment by zaccherinij** [comment]
@yojedesign Hi, did you get a chance to check out @andrei-stoian-zama's message above? Without any feedback from you, we will close this grant proposal. Let us know if you have any question! Cheers!

**Comment by yojedesign** [comment]
Thanks for your question this our answer :

The pipeline we envision for our project involves several key components,
including data preprocessing, feature extraction, model training, and
inference. In terms of model architecture, we aim to implement a deep
learning-based approach, specifically leveraging convolutional neural
networks (CNNs) for feature extraction and recurrent neural networks (RNNs)
for sequence modeling, given the sequential nature of our data.As for the
use of Fully Homomorphic Encryption (FHE), we intend to incorporate it
primarily into the data preprocessing and inference stages of the pipeline.
FHE will allow us to perform secure computations on encrypted data,
ensuring privacy and confidentiality throughout the process. Additionally,
we plan to explore techniques for optimizing the FHE model architecture to
balance computational efficiency and security.Overall, our goal is to
develop a robust and privacy-preserving machine learning pipeline that can
effectively handle sensitive data while maintaining state-of-the-art
performance.


*Cheers,*
Bacely YoroBI
*NEW TOMOROW LEADERS  2015 - CRANSMONTANA FORUM                   *
Former CEO * @ *SocialSpot  <http://www.socialspot.ci/> Projet *Labellisé *
 "* ICI2014 <http://ici2014.com/forum-ici-2014/concours-start-up/>*"
Initiative Gouvernementale  & " *CEPICI <http://www.cepici.gouv.ci>*  "

*--- Awarded FORUM ICI 2014 Startup Competition --**TECHCAMP TRAINER ,
eDiplomacy*U.S---*
Interview *BBC <https://soundcloud.com/amn/valerie-bony-x-bbc-x-abidjan> |** El
Païs
<http://blogs.elpais.com/africa-no-es-un-pais/2013/06/lared-marfilena-3.html>
| VOA
<http://www.voanews.com/content/ivory-coast-web-mayor-campaigns-against-cybercrime/1669048.html>
| RNW
<http://www.rnw.nl/afrique/article/la-d%C3%A9mocratisation-de-linternet-selon-bacely-yorobi>|
RFI
<http://www.rfi.fr/emission/20121229-1-carrefour-possibles-afrique-2012-1er-volet>|
TYCOON
<https://plus.google.com/u/0/photos/111694467776564164081/albums/6009747749536396353>|**AfriqueIT
News
<http://afriqueitnews.com/2012/11/07/decouvrez-socialspot-une-start-up-ivoirienne-qui-propose-de-sponsoriser-lacces-a-internet-genius/>
|
RTI TV <https://www.youtube.com/watch?v=_X2yMuEERA0>*
*              | CDP AFRIQUE
<https://www.youtube.com/watch?v=p13OHt-mAMI> | SmartMonkey TV
<https://www.youtube.com/watch?v=Xg-wLEXII1w&list=UUjZKApAFkRV149mU03N5pkw> |
InternetSanSFrontiere
<http://www.internetsansfrontieres.org/Une-semaine-a-Abidjan-rencontre-avec-Bacely-Yorobi_a531.html>*
*              |Jeune Afrique
<http://economie.jeuneafrique.com/regions/afrique-subsaharienne/22805-technologie--la-cote-divoire-a-lecole-de-linnovation.html>|
Rue89
<http://rue89.nouvelobs.com/2014/06/14/les-satellites-google-vus-dafrique-lappetit-vient-mangeant-252843>
|
TechAfrique
<http://techafrique.startupbrics.com/internet-gratuit-social-spot-startup-afrique/>|ArkansasBusiness
<http://www.arkansasbusiness.com/article/100483/video-made-by-few>|TECHCAMP
<http://techcampglobal.org/techcamp-mali-a-new-partnership-in-support-of-civil-society/>*

   - *Founder and Internet Strategist at *http://www.socialspote.com
   - *Founder and Catalyst at <http://goog_1477044994>*
   http://www.connectxglobal.org
- *Co-Founder and Chairman at <http://goog_1477044996>*
   http://www.thegamecamp.org
   - *Blogger and Writer at *http://www.bacelyyorobi.ci
- *Côte d'Ivoire *Abidjan* |* *(+225) 06 86 52 09 | **USA *San Francisco  *|
   + 1 (415) 841-2953*
   - *Twitter :* @ Yojedesign <http://twitter.com/yojedesign>| *FB :* @
   yojedesign <http://facebook.com/yojedesign> | *G+: * Bacely
   <http://gplus.to/bacely> | *About : http://about.me/bacelyy
   <http://about.me/bacelyy>*
   - *Design : Behance <http://behance.net/yojedesign> | **Dribbble
   <https://dribbble.com/yojedesign>**Writing* :* Pressfolio
   <http://bacely.pressfolios.com/> **Coding* : *Github*
   <http://github.com/yojedesign>





Le lun. 22 avr. 2024 à 15:54, Andrei Stoian ***@***.***> a
écrit :

**Comment by yojedesign** [comment]
Yes I answer it.

*Cheers,*
Bacely YoroBI
*NEW TOMOROW LEADERS  2015 - CRANSMONTANA FORUM                   *
Former CEO * @ *SocialSpot  <http://www.socialspot.ci/> Projet *Labellisé *
 "* ICI2014 <http://ici2014.com/forum-ici-2014/concours-start-up/>*"
Initiative Gouvernementale  & " *CEPICI <http://www.cepici.gouv.ci>*  "

*--- Awarded FORUM ICI 2014 Startup Competition --**TECHCAMP TRAINER ,
eDiplomacy*U.S---*
Interview *BBC <https://soundcloud.com/amn/valerie-bony-x-bbc-x-abidjan> |** El
Païs
<http://blogs.elpais.com/africa-no-es-un-pais/2013/06/lared-marfilena-3.html>
| VOA
<http://www.voanews.com/content/ivory-coast-web-mayor-campaigns-against-cybercrime/1669048.html>
| RNW
<http://www.rnw.nl/afrique/article/la-d%C3%A9mocratisation-de-linternet-selon-bacely-yorobi>|
RFI
<http://www.rfi.fr/emission/20121229-1-carrefour-possibles-afrique-2012-1er-volet>|
TYCOON
<https://plus.google.com/u/0/photos/111694467776564164081/albums/6009747749536396353>|**AfriqueIT
News
<http://afriqueitnews.com/2012/11/07/decouvrez-socialspot-une-start-up-ivoirienne-qui-propose-de-sponsoriser-lacces-a-internet-genius/>
|
RTI TV <https://www.youtube.com/watch?v=_X2yMuEERA0>*
*              | CDP AFRIQUE
<https://www.youtube.com/watch?v=p13OHt-mAMI> | SmartMonkey TV
<https://www.youtube.com/watch?v=Xg-wLEXII1w&list=UUjZKApAFkRV149mU03N5pkw> |
InternetSanSFrontiere
<http://www.internetsansfrontieres.org/Une-semaine-a-Abidjan-rencontre-avec-Bacely-Yorobi_a531.html>*
*              |Jeune Afrique
<http://economie.jeuneafrique.com/regions/afrique-subsaharienne/22805-technologie--la-cote-divoire-a-lecole-de-linnovation.html>|
Rue89
<http://rue89.nouvelobs.com/2014/06/14/les-satellites-google-vus-dafrique-lappetit-vient-mangeant-252843>
|
TechAfrique
<http://techafrique.startupbrics.com/internet-gratuit-social-spot-startup-afrique/>|ArkansasBusiness
<http://www.arkansasbusiness.com/article/100483/video-made-by-few>|TECHCAMP
<http://techcampglobal.org/techcamp-mali-a-new-partnership-in-support-of-civil-society/>*

   - *Founder and Internet Strategist at *http://www.socialspote.com
   - *Founder and Catalyst at <http://goog_1477044994>*
   http://www.connectxglobal.org
- *Co-Founder and Chairman at <http://goog_1477044996>*
   http://www.thegamecamp.org
   - *Blogger and Writer at *http://www.bacelyyorobi.ci
- *Côte d'Ivoire *Abidjan* |* *(+225) 06 86 52 09 | **USA *San Francisco  *|
   + 1 (415) 841-2953*
   - *Twitter :* @ Yojedesign <http://twitter.com/yojedesign>| *FB :* @
   yojedesign <http://facebook.com/yojedesign> | *G+: * Bacely
   <http://gplus.to/bacely> | *About : http://about.me/bacelyy
   <http://about.me/bacelyy>*
   - *Design : Behance <http://behance.net/yojedesign> | **Dribbble
   <https://dribbble.com/yojedesign>**Writing* :* Pressfolio
   <http://bacely.pressfolios.com/> **Coding* : *Github*
   <http://github.com/yojedesign>

**Comment by andrei-stoian-zama** [comment]
We'd like to determine some criteria for success of the solution that you will submit for your grant. 

1. Could you list some datasets that are relevant for your task and the expected accuracy you think you can achieve? 
2. Could you describe the operational setting for a potential real-life usage of your solution?

**Comment by zaccherinij** [comment]
Hey @yojedesign,

Thank you very much for your interest in what we do at Zama, and your proposition for a grant. For now, we will not follow up with your proposition. But we invite you to keep an eye on this repository as we will launch new bounties soon, if you're interested in playing with Zama libs.

Cheers,
JZ
