### ISSUE TITLE
Floating point mathematics for TFHE-rs

### ISSUE THREAD

**Issue by Lcressot** [zama-ai/bounty-and-grant-program#92]
# Zama Bounty Program: Proposition

- Library targeted:
TFHE-rs

- Overview:
I propose to implement a class to represent signed float numbers in tfhe-rs (using a quantized representation) along with elementary math functions for these numbers. This will make the computation of basic statistics (such as mean and variance) possible for encrypted numbers.

- Description:
1. **Signed quantized floats**:  
The numbers will be represented as arrays of 1 block integer ciphertexts, with chosen maximum value and float precision.  
Elementary operators will be coded: equality, gt,ge,lt,le, addition, subtraction, multiplication, division.
Clear conversion from and toward rust float will be provided.  

*Note*: This part will be a rust adaptation of quantized floating point numbers developed for concrete (see `QFloat` class in [matrix inversion bounty](https://github.com/Lcressot/matrix-inversion)). It will be faster because it will use maximaly massive parallelization with rayon. While a lot of the code will be reused, rust adaptation is not straightforward and is expected to need more code than the concrete python version because concrete python does a lot of operations internally.

2. **Math operations**:  
	i. sum, mean, scalar product of vectors of encrypted floats  
	ii. Integer exponentiation: pow(x: encryptedFloat, y: int) where x is an encrypted float and y a clear integer.  
	iii. Cos, sin, tan for encrypted floats  
	iv. Variance, median for arrays of encrypted floats  

3. **Square root** (with newton-raphson method) + standard deviation of encrypted floats

4. A main with tests for 1., 2. and 3.

- Reward (split by milestones):
1. 4k $ (~2-3 full weeks)
2. 2k $ (~5-7 days)
3. 1k $ (~2-3 days) 
4. 0$ (included)

- Related links and reference:
[Matrix inversion bounty](https://github.com/Lcressot/matrix-inversion)

**Comment by aquint-zama** [comment]
Hello @Lcressot,

Thank you for this proposition. We are currently reviewing the regular bounties but we will get back to you
soon about your proposition.

**Comment by aquint-zama** [comment]
Hello @Lcressot,

Thank you for your suggestion. While the idea looks interesting, it's still an open area of research internally and we are yet not sure about the proper approach for supporting decimal numbers.

Also we are encouraging grants that are actually applications using tfhe-rs, rather than contribution to the code, which can be harder to integrate and maintain over time on our side.

For these reasons we won't go further with this suggestion.

Cheers,

**Comment by Lcressot** [comment]
Hello.Ok, thank you for the explanation.Best,LoicLe 9 févr. 2024 à 15:53, Alex Quint ***@***.***> a écrit :﻿
Hello @Lcressot,
Thank you for your suggestion. While the idea looks interesting, it's still an open area of research internally and we are yet not sure about the proper approach for supporting decimal numbers.
Also we are encouraging grants that are actually applications using tfhe-rs, rather than contribution to the code, which can be harder to integrate and maintain over time on our side.
For these reasons we won't go further with this suggestion.
Cheers,
