### ISSUE TITLE
Create an on chain DRM system using Zama's fhEVM

### ISSUE THREAD

**Issue by zaccherinij** [zama-ai/bounty-and-grant-program#93]
## Overview

Zama's fhEVM allows control on who has access to particular encrypted data. For example, in a NFT contract, only the designated owner can access certain encrypted information. The objective of this bounty is to develop an application that utilizes this capability to protect digital assets (files, movies...).

## Submission
1️⃣ Want to solve this bounty? <a href="https://zama.ai/bounty-program" target="_blank">Register here</a>.
2️⃣ Ready to submit your solution? <a href="https://zama.ai/bounty-program" target="_blank">Submit here</a>.
🗓️ Submission deadline: May 12th, 2024.

## What we expect

The application will create NFTs containing encrypted metadata and a private key. This key grants the NFT owner exclusive access to various digital content, including files, movies, and exclusive media. The content should be stored in some decentralized way, and the more resilient, the better.

### Requirements:
* **Smart Contract**: Write smart contracts in Solidity, running on fhEVM.
* **UI Interface**: Create a user-friendly UI for minting and private content interaction.
* **Deployment**: The smart contract should be compatible with the Zama fhEVM devnet. The web application should be accessible online with a Metamask wallet. Usage of thrid-party blockchain is recommended for storage (IPFS, FileCoin, ...).
* **Use of fhEVM**: The NFT should employ hidden information, showcasing the capabilities of the fhEVM.

### Judging Criteria:
* **Use of Zama's fhEVM**: Effectiveness in demonstrating the unique features of the Zama's fhEVM.
* **Complexity**: The complexity of the project: different private key per NFT, upload of encrypted content on minting, encrypted video stream, usage of the NFT ownership in another contract...
* **Submission Quality**: Emphasis on clear code and polished UI.

### 🥇Best submission: up to €5,000
To be considered best submission, a solution must be efficient, effective and demonstrate a deep understanding of the core problem. Alongside the technical correctness, it should also be submitted with a clean code, clear explanations and a complete documentation.

### 🥈Second-best submission: up to €3,000
For a solution to be considered the second best submission, it should be both efficient and effective. The code should be neat and readable, while its documentation might not be as exhaustive as the best submission, it should cover the key aspects of the solution.

### 🥉Third-best submission: up to €2,000
The third best submission is one that presents a solution that effectively tackles the challenge at hand, even if it may have certain areas of improvement in terms of efficiency or depth of understanding. Documentation should be present, covering the essential components of the solution.

## Related links and references

- [fhEVM repository](https://github.com/zama-ai/fhevm)
- [fhEVM documentation](https://docs.zama.ai/fhevm)
- [Confidential ERC20 Blog post](https://www.zama.ai/post/confidential-erc-20-tokens-using-homomorphic-encryption)
- [On-chain Blind Auctions Blog post](https://www.zama.ai/post/on-chain-blind-auctions-using-homomorphic-encryption)

## Questions?
Do you have a specific question about this bounty or Zama's fhEVM? 
- Join the live conversation on the [FHE.org discord server](https://discord.fhe.org/) 
- Ask technical question on our [Community forum](https://community.zama.ai)
- Join the general discussion on the Telegram group: [fhEVM explorers](https://t.me/+Ojt5y-I7oR42MTkx)
- And feel free to reach out privately at: bounty@zama.ai

**Comment by Horlarmmy** [comment]
Nice

**Comment by gaupoit** [comment]
Interested in

**Comment by lakshya-dhariwal** [comment]
Hey @zaccherinij can you mention the exact time the submissions on this close
As it can differ by almost a day depending on the timezone

**Comment by pratham-bhatnagar** [comment]
Hey @zaccherinij,
With DRM system do you mean specific Digital rights management system, or we can have encrypted access Drive. We have already stared implementing a Encrypted Drive with FHE based 2FA. Will this idea fit in this submission?

**Comment by zaccherinij** [comment]
A friendly reminder that the Submission deadline is May 12th, 2024 at 23:59 AoE (Anywhere on Earth). Good luck!

**Comment by immortal-tofu** [comment]
> Hey @zaccherinij, With DRM system do you mean specific Digital rights management system, or we can have encrypted access Drive. We have already stared implementing a Encrypted Drive with FHE based 2FA. Will this idea fit in this submission?

The idea is to store an encryption key (AES or another scheme) as an encrypted uint. This is the core idea.
Then, you can create a use case around that: this key is stored as an NFT, and only the owner can decrypt the key. This key could allow the owner to see a movie or photos for example.

**Comment by zaccherinij** [comment]
Thank you to everyone who submitted to the Zama Bounty Program Season 5. Our team will review them and give some initial feedbacks in the coming days! 
Cheers.
